export type ClientModel = {
  id: any;
  phone?: any;
  name: string;
  goals?: string;
  notes?: string;
  email?: string;
  login: boolean;
  height?: string;
  weight?: string;
  category: string;
  injuries?: string;
  password?: string;
  lastName?: string;
  subCategory: string;
  initialDate?: string;
  expiredDate?: string;
  planAssigned?: string;
  medicalConditions?: string;
};
